[package]
name = "r86-sim"
version = "0.1.0"
authors = ["McLytar <gianluca.brian.94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
tokio = { version = "1.2.0", features = ["full"] }